### ISSUE TITLE
infra: better and platform-independent way to install mole

### ISSUE THREAD

**Issue by davrodpin** [davrodpin/mole#19]
The project should have a shell script that, once executed, would detect the system architecture then download the proper binary then install it.

How to find OS name and architecture:

* macOS

```sh
$ uname -sm
Darwin x86_64
```

* linux

```sh
$ uname -sm
Linux x86_64
```

The installation process would look like to:

```sh
$ bash <(curl -fsSL https://raw.githubusercontent.com/davrodpin/mole/master/tools/install)
```

**Comment by ricardoseriani** [comment]
I'll can take this one, if  possible.

The script will also uncompress the .tar.gz ?
If so, what directory it will put the binary ?

**Comment by ricardoseriani** [comment]
Thanks for the instructions.
I'll work in this and send a PR.

**Comment by ricardoseriani** [comment]
While I'm working on this, the only "problem" I found is that, in order to extract the files in `/usr/local/bin` it may require administrative privileges.
It's ok to ask for permission using sudo, or you prefer another option ? (like extract in the current folder, although in that case the file move has to be done manually).

**Comment by davrodpin** [comment]
To provide a better experience while installing the tool, let's use `sudo`, but let's use it only on the command that copies the binary to `/usr/local/bin` to avoid security-related issues.
