### ISSUE TITLE
Inconsistencies in duplicated auxilliary functions

### ISSUE THREAD

**Issue by awnumar** [davrodpin/mole#82]
https://github.com/davrodpin/mole/blob/f78f0cc222bb9310888dfac30c297950f6daaf25/tunnel/tunnel.go#L367-L413

These four functions seem to have the _intention_ of having identical functionality.

1. If given value is non-empty, return it.
2. Else return resolved value.

However `reconcileHostname` diverges from this pattern by prioritizing `resolvedHostname` instead of `givenHostname` like the others do.

If this is a mistake, I suggest the following function to replace all four of them:

```go
func reconcileValue(given, resolved string) string {
    if given != "" {
        return given
    }
    
    return resolved
}
```

**Comment by davrodpin** [comment]
@awnumar, `reconcileHostname` has to give precedence to the resolved value because of names configured on the ssh config file. 

Other parameters like port, user and key work as opposite: the precedence should be the given value and if that is not provided, then the application should use the resolved one.

I agree the code could be redesigned a bit to have a single function instead of five.
The only thing I would change on your proposal is to replace `given` with `precedent` and `resolved` with `subsequent` so the `given` vs. `resolved` value precedence could be decided by the client of the function.
